version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app/src
      - ./output:/app/output
    env_file:
      - .env

  dashboard:
    build:
      context: .
      dockerfile: Dockerfile.dashboard
    ports:
      - "8501:8501"
    volumes:
      - ./dashboard:/app/dashboard
    depends_on:
      - api

# Note: Dockerfiles and .env file need to be created for a complete setup.
# This is a placeholder as requested.
