proxies:
  - ip: "192.168.1.100"
    port: 8080
  - ip: "192.168.1.101"
    port: 8080
user_agents:
  - "Mozilla/5.0 (Windows NT 10.0; Win64; x64) Chrome/120.0.0.0"
  - "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) Safari/605.1.15"
